//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Photon.SocketServer;
using Photon.SocketServer.Annotations;

namespace Photon.Common.Authentication
{
    [SettingsMarker("Photon:Authentication")]
    public class Settings
    {
        // Explicit static constructor to tell C# compiler
        // not to mark type as beforefieldinit
        static Settings()
        { }

        public static Settings Default { get; } = ApplicationBase.GetConfigSectionAndValidate<Settings>("Photon:Authentication");

        public int AuthTokenExpirationSeconds { get; set; } = 1800;

        public string AuthTokenKey { get; set; } = string.Empty;

        public string HMACTokenKey { get; set; } = string.Empty;

        public bool MissingClientAuthenticationTypeIsTypeCustom { get; set; } = false;

        public int AuthTimeout { get; set; } = 20_000;//20 seconds

    }
}
